### PR TITLE
Create 2022-10-04-written-reply-to-pq-on-the-30-by-30-goal.md

### PR DESCRIPTION
**Pull request by AlvinaWang**
For approval.

### CODE REVIEW

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Review by harieazhari — APPROVED** [review]
Ok!

**Pull request merged**
