### PR TITLE
Create 2022-10-03-written-reply-to-pq-on-national-recycling-programme.md

### PR DESCRIPTION
**Pull request by AlvinaWang**
For approval.

### CODE REVIEW

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Review by harieazhari — APPROVED** [review]
Appoved

**Pull request merged**
