### PR TITLE
Create 2022-10-20-written-reply-to-pq-on-high-rise-littering.md

### PR DESCRIPTION
**Pull request by AlvinaWang**
For approval.

### CODE REVIEW

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Review by ianmakwei — APPROVED** [review]

**Comment by AlvinaWang** [comment]
For approval.

**Comment by AlvinaWang** [comment]
For approval.

**Pull request merged**
